version: '3.4' # For compatibility with older Docker versions

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - '9990:9980'
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=dms_user_10d2d88:Zz896583039@rm-bp1fdi4r1e46fw2oqxo.mysql.rds.aliyuncs.com:3306/new_api?parseTime=true
      - LOG_SQL_DSN=dms_user_10d2d88:Zz896583039@rm-bp1fdi4r1e46fw2oqxo.mysql.rds.aliyuncs.com:3306/new_api_log?parseTime=true
      - REDIS_CONN_STRING=redis://z896583039:Zz896583039@r-bp1m2huxc73q32zytrpd.redis.rds.aliyuncs.com:6379/0 
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true # 是否启用错误日志记录
      - BATCH_UPDATE_ENABLED=true # 是否启用批量更新 batch update enabled
      - STREAMING_TIMEOUT=300  # 流模式无响应超时时间，单位秒，默认120秒，如果出现空补全可以尝试改为更大值 Streaming timeout in seconds, default is 120s. Increase if experiencing empty completions
      - SESSION_SECRET=zhouxingguo
      - SYNC_FREQUENCY=60

    healthcheck:
      test:
        [
          'CMD-SHELL',
          "wget -q -O - http://localhost:9980/api/status | grep -o '\"success\":\\s*true' || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3